# values.yaml
replicaCount: 1

image:
  repository: ghcr.io/kairoaraujo/cowservice
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: cowservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
service:
  type: ClusterIP
  port: 8000

nginx:
  image:
    repository: bitnami/nginx
    tag: 1.27.4
    pullPolicy: IfNotPresent
  enabled: true
  service:
    type: ClusterIP
    port: 80
  staticSitePVC: cowsay-outputs-pvc
  ingress:
    enabled: true
    hostname: download.local
  
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi