apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cowsay-outputs-pvc
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
