name: Release Workflow

permissions:
  id-token: write # Required for requesting the JWT
  contents: write # Allows creating releases and uploading assets
  
on:
  push:
    tags:
      - 'v*' # Only trigger on version tags
      
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.22.x

      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: 3.13
      
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cyclonedx-bom build

      - name: Witness Run
        uses: testifysec/witness-run-action@79320a907f611f2fb40ced8e13c66af988b2d9db
        with:
          step: build
          enable-archivista: false
          enable-sigstore: true
          command: python -m build --sdist --wheel --outdir dist/ .
          outfile: attestation-cowservice-build.json

      - name: Witness Run
        uses: testifysec/witness-run-action@79320a907f611f2fb40ced8e13c66af988b2d9db
        with:
          step: sbom
          enable-archivista: false
          enable-sigstore: true
          command: cyclonedx-py pipenv > sbom.json
          outfile: attestation-cowservice-sbom.json

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            *.json
            dist/*